version: '3.1'
services:
  api:
    container_name: nest_api
    build: .
    env_file: 
      - .env
    ports: 
      - ${PORT}:${PORT}
      - 9229:9229
    volumes: 
      - .:/usr/src/app  
      - /usr/src/app/node_modules
    environment: 
        DB_HOST: database
        DB_PORT: 5432
    networks: 
      - backend
    depends_on: 
      - database      

  database:
    image: postgres:9.6-alpine
    container_name: db_nest
    networks: 
      - backend
    env_file: 
      - .env
    environment: 
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes: 
      - api_db_data:/var/lib/postgresql/data
networks: 
  backend:
volumes: 
  api_db_data: