version: '3.1'
services:
  api:
    container_name: nest_api
    build: .
    restart: always
    env_file: 
      - .env
    ports: 
      - ${PORT}:${PORT}
    volumes: 
      - .:/home/api  
      - /home/api/node_modules
    environment: 
        DB_HOST: database
        DB_PORT: 5432

  database:
    image: postgres:13
    container_name: db_nest
    restart: always
    env_file: 
      - .env
    environment: 
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:${DB_PORT}
